"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def sol_1():
    x = 4000000
    fib = [1, 1]
    fib_next = fib[-1] + fib[-2]
    while fib_next < x:
        fib.append(fib_next)
        fib_next = fib[-1] + fib[-2]
    return sum(fib[2::3])


print(sol_1())
